services:
  goa-sandbox:
    build:
      context: .
      secrets: [ github_token ]
    ports: [ "8088" ] # Don't expose the container port
    environment:
      JAVA_OPTS: "-Xms64m -Xmx384m"
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongo:27017/goasandboxdb?authSource=admin
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://host.docker.internal:8080/api/goa-user/oauth2/jwks
      APP_OAUTH2_TOKEN_URI: http://host.docker.internal:8080/api/goa-user/oauth2/token
    networks: [ goa ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

networks:
  goa:
    external: true

secrets:
  github_token:
    environment: GITHUB_TOKEN

# Windows PowerShell
#> $env:GITHUB_TOKEN="xxxx"   echo $env:GITHUB_TOKEN
# Para saber si el token esta habilitado
#> curl.exe -H "Authorization: Bearer $env:GITHUB_TOKEN" https://api.github.com/user

#> docker compose up --build -d


#> docker logs -f goa-sandbox
